# Generated by Django 3.0.7 on 2020-06-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_todoadder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoadder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
