# Generated by Django 3.0.7 on 2020-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200629_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoadder',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
